lastupdatecheck: 0
recentrepos:
    - /home/neimog/Documents/Git/dotfiles
startuppopupversion: 5
didshowhunkstaginghint: true
lastversion: 0.57.0
customcommandshistory:
    - q
    - ""
    - q!
    - minor updates related with py4pd changes
    - 'commit '
    - fix the pd.print for multiple args
    - '?'
hidecommandlog: false
